### ISSUE TITLE
It broke bro

### ISSUE THREAD

**Issue by Xnopyt** [kxpler442b/andromeda#1]
it no work, this might help https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by kxpler442b** [comment]
nah bro its fine trus me bro swear down its turbo finger lickin' brill fam

**Comment by Xnopyt** [comment]
nah bro it yeet ma cat init

**Comment by kxpler442b** [comment]
swear down bro thats peak

**Comment by kxpler442b** [comment]
let me check the js

**Comment by kxpler442b** [comment]
this should fix it https://www.vets4pets.com/

**Comment by Xnopyt** [comment]
https://www.youtube.com/watch?v=TsHrJM1AExc

**Comment by Xnopyt** [comment]
also my cat is now on fire
